#-Gen Timers



#-GENERATOR Effects and Particles

effect @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] invisibility 255 255 true
effect @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] invisibility 255 255 true
effect @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] invisibility 255 255 true
effect @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] invisibility 255 255 true
effect @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] invisibility 255 255 true
effect @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] invisibility 255 255 true
effect @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] invisibility 255 255 true

effect @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] resistance 255 255 true
effect @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] resistance 255 255 true
effect @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] resistance 255 255 true
effect @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] resistance 255 255 true
effect @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] resistance 255 255 true
effect @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] resistance 255 255 true
effect @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] resistance 255 255 true

execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~~0.5~ particle minecraft:sculk_charge_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~~0.5~ particle minecraft:villager_happy
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:honey_drip_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~~0.5~ particle minecraft:falling_dust_gravel_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~~0.5~ particle minecraft:endrod
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~~0.5~ particle minecraft:dragon_breath_trail
#Other cool particles - sculk_sensor_redstone_particle
#soul_particle

#top left corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~0.5~1~0.5 particle minecraft:balloon_gas_particle
#top right corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~-0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~-0.5~1~0.5 particle minecraft:balloon_gas_particle

#bottom left corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~0.5~1~-0.5 particle minecraft:balloon_gas_particle
#bottom right corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~-0.5~1~-0.5 particle minecraft:balloon_gas_particle


#btop left corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~0.5~~0.5 particle minecraft:balloon_gas_particle
#btop right corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~-0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~-0.5~~0.5 particle minecraft:balloon_gas_particle

#bbelow left corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~0.5~~-0.5 particle minecraft:balloon_gas_particle
#bbottom right corner
execute @e[type=rabbit,name="§l§bDiamond §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §bDiamond Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§aEmerald §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §aEmerald Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§gGold §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §gGold Ore§r§f \n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§8Coal §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §8Coal Ore§r§f\n - §7Stone§r§f\n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§7Netherite §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§7Ancient Debris§r§f\n - §cNetherrack§r§f\n - §fQuartz Ore§r§f\n - §gNether Gold Ore§r\n §bBlock Rate: §c3s"] ~-0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§fIron §dGen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §fIron Ore§r§f\n - §7Stone§r§f \n - §7Cobblestone§r\n §bBlock Rate: §c3s"] ~-0.5~~-0.5 particle minecraft:balloon_gas_particle
execute @e[type=rabbit,name="§l§cSPECIAL §6Gen§r\n§cCAUTION: Once placed you CANNOT pick up a generator!§f\n--------------------------------\n§aContains:§f\n - §l§dAmethyst Block§r§f\n - §6Copper Block§r§f\n - §7Ancient Debris§r§f\n - §aEmerald Block§r§f\n - §bDiamond Block§r\n §bBlock Rate: §c3s"] ~-0.5~~-0.5 particle minecraft:balloon_gas_particle


